created wishlist and their corresponding views
rishabhharod/Erratic-Project pull request #6
Opened 2024-08-27 13:26 UTC by rishabhharod

2024-08-27 13:50 UTC, vinayaklovanshi requested changes

2024-08-27 13:50 UTC, vinayaklovanshi commented on app/controllers/carts_controller.rb
> +  def index
Add line after callbacks

2024-08-27 13:50 UTC, vinayaklovanshi commented on app/controllers/wishlist_items_controller.rb
> +  def create
Add extra space

2024-08-27 13:50 UTC, vinayaklovanshi commented on app/controllers/wishlists_controller.rb
> +  def show
Add proper spacing for all the methods

2024-08-27 13:50 UTC, vinayaklovanshi commented on app/views/wishlists/show.html.erb
> +<style>
Add css in css file not in this file.

2024-08-28 07:12 UTC, rishabhharod commented on app/controllers/carts_controller.rb
> +  def index
done sir

2024-08-28 07:12 UTC, rishabhharod commented on app/controllers/wishlist_items_controller.rb
> +  def create
done

2024-08-28 07:13 UTC, rishabhharod commented on app/controllers/wishlists_controller.rb
> +  def show
spacing added

2024-08-28 07:13 UTC, rishabhharod commented on app/views/wishlists/show.html.erb
> +<style>
done sir

2024-08-28 07:44 UTC, merged